-- MySQL Script generated by MySQL Workbench
-- Wed 14 Mar 2018 11:14:44 PM CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema datawarehousedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema datawarehousedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `datawarehousedb` DEFAULT CHARACTER SET utf8 ;
USE `datawarehousedb` ;

-- -----------------------------------------------------
-- Table `datawarehousedb`.`Alcohol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`Alcohol` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`Alcohol` (
  `alcoholid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `alcohol` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`alcoholid`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`AllergyList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`AllergyList` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`AllergyList` (
  `allergylistid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `allergylist` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`allergylistid`))
ENGINE = InnoDB
AUTO_INCREMENT = 89
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`CitizenStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`CitizenStatus` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`CitizenStatus` (
  `citizenid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `citizen` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`citizenid`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`City`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`City` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`City` (
  `cityid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`cityid`))
ENGINE = InnoDB
AUTO_INCREMENT = 54
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`EmergencyR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`EmergencyR` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`EmergencyR` (
  `emergencyrid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `emergencyr` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`emergencyrid`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`Ethnicity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`Ethnicity` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`Ethnicity` (
  `ethnicityid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ethnicity` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`ethnicityid`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`Gender`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`Gender` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`Gender` (
  `genderid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `gender` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`genderid`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`PrimaryLanguage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`PrimaryLanguage` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`PrimaryLanguage` (
  `languageid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `language` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`languageid`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`Race`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`Race` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`Race` (
  `raceid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `race` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`raceid`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`State`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`State` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`State` (
  `stateid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `state` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`stateid`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`Zip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`Zip` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`Zip` (
  `zipid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `zip` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`zipid`))
ENGINE = InnoDB
AUTO_INCREMENT = 68
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`Patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`Patient` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`Patient` (
  `patientid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(50) NULL DEFAULT NULL,
  `lname` VARCHAR(50) NULL DEFAULT NULL,
  `genderid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `raceid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `ethnicityid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `dob` DATE NULL DEFAULT NULL,
  `address_street` VARCHAR(50) NULL DEFAULT NULL,
  `cityid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `stateid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `zipid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `emergencyrid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `phone_number` VARCHAR(50) NULL DEFAULT NULL,
  `email_address` VARCHAR(50) NULL DEFAULT NULL,
  `emergency_name` VARCHAR(50) NULL DEFAULT NULL,
  `emergency_number` VARCHAR(50) NULL DEFAULT NULL,
  `citizenid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `languageid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`patientid`),
  INDEX `Gender.genderid_Patient.genderid` (`genderid` ASC),
  INDEX `Race.raceid_Patient.raceid` (`raceid` ASC),
  INDEX `Ethnicity.ethnicityid_Patient.ethnicityid` (`ethnicityid` ASC),
  INDEX `City.cityid_Patient.cityid` (`cityid` ASC),
  INDEX `State.stateid_Patient.stateid` (`stateid` ASC),
  INDEX `Zip.zipid_Patient.zipid` (`zipid` ASC),
  INDEX `EmergencyR.emergencyrid_Patient.EmergencyRid` (`emergencyrid` ASC),
  INDEX `CitizenStatus.citizenid_Patient.citizenid` (`citizenid` ASC),
  INDEX `PrimaryLanguage.languageid_Patient.languageid` (`languageid` ASC),
  CONSTRAINT `CitizenStatus.citizenid_Patient.citizenid`
    FOREIGN KEY (`citizenid`)
    REFERENCES `datawarehousedb`.`CitizenStatus` (`citizenid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `City.cityid_Patient.cityid`
    FOREIGN KEY (`cityid`)
    REFERENCES `datawarehousedb`.`City` (`cityid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `EmergencyR.emergencyrid_Patient.EmergencyRid`
    FOREIGN KEY (`emergencyrid`)
    REFERENCES `datawarehousedb`.`EmergencyR` (`emergencyrid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Ethnicity.ethnicityid_Patient.ethnicityid`
    FOREIGN KEY (`ethnicityid`)
    REFERENCES `datawarehousedb`.`Ethnicity` (`ethnicityid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Gender.genderid_Patient.genderid`
    FOREIGN KEY (`genderid`)
    REFERENCES `datawarehousedb`.`Gender` (`genderid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `PrimaryLanguage.languageid_Patient.languageid`
    FOREIGN KEY (`languageid`)
    REFERENCES `datawarehousedb`.`PrimaryLanguage` (`languageid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Race.raceid_Patient.raceid`
    FOREIGN KEY (`raceid`)
    REFERENCES `datawarehousedb`.`Race` (`raceid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `State.stateid_Patient.stateid`
    FOREIGN KEY (`stateid`)
    REFERENCES `datawarehousedb`.`State` (`stateid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Zip.zipid_Patient.zipid`
    FOREIGN KEY (`zipid`)
    REFERENCES `datawarehousedb`.`Zip` (`zipid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 588
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`Colonoscopy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`Colonoscopy` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`Colonoscopy` (
  `colonoscopyid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `patientid` BIGINT(20) UNSIGNED NOT NULL,
  `colonoscopy` DATE NULL DEFAULT NULL COMMENT 'Date of the patient\'s most recent colonoscopy',
  PRIMARY KEY (`colonoscopyid`),
  INDEX `Patient.patientid_Colonoscopy.patientid` (`patientid` ASC),
  CONSTRAINT `Patient.patientid_Colonoscopy.patientid`
    FOREIGN KEY (`patientid`)
    REFERENCES `datawarehousedb`.`Patient` (`patientid`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`CooperGreen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`CooperGreen` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`CooperGreen` (
  `cooperid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cooper` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`cooperid`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COMMENT = 'Table semantics changed to ask about health first card (UAB-specific)';


-- -----------------------------------------------------
-- Table `datawarehousedb`.`CurrentEmployment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`CurrentEmployment` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`CurrentEmployment` (
  `employmentid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `employment` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`employmentid`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`Disability`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`Disability` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`Disability` (
  `disabilityid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `disability` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`disabilityid`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`EducationLevel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`EducationLevel` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`EducationLevel` (
  `educationid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `education` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`educationid`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`FoodStamp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`FoodStamp` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`FoodStamp` (
  `foodstampid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `foodstamp` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`foodstampid`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`HeadofHousehold`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`HeadofHousehold` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`HeadofHousehold` (
  `housestatid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `housestat` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`housestatid`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`HomeType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`HomeType` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`HomeType` (
  `hometypeid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `hometype` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`hometypeid`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`MedicalInsurance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`MedicalInsurance` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`MedicalInsurance` (
  `insuranceid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `insurance` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`insuranceid`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`PrimaryPhysician`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`PrimaryPhysician` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`PrimaryPhysician` (
  `physicianid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `physician` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`physicianid`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`RelationshipStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`RelationshipStatus` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`RelationshipStatus` (
  `relationshipid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `relationship` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`relationshipid`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`Transport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`Transport` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`Transport` (
  `transportid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `transport` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`transportid`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`Veteran`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`Veteran` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`Veteran` (
  `veteranid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `veteran` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`veteranid`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`SocialHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`SocialHistory` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`SocialHistory` (
  `sid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `householdincome` BIGINT(20) NULL DEFAULT NULL,
  `numchildren` BIGINT(20) NULL DEFAULT NULL,
  `numfammember` BIGINT(20) NULL DEFAULT NULL,
  `heareab` TEXT NULL DEFAULT NULL,
  `cooperid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `physicianid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `educationid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `housestatid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `insuranceid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `disabilityid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `veteranid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `employmentid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `relationshipid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `alcoholid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `foodstampid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `hometypeid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `transportid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `patientid` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`sid`),
  INDEX `Patient.patientid_SocialHistory.patientid` (`patientid` ASC),
  INDEX `CooperGreen.cooperid_SocialHistory.cooperid` (`cooperid` ASC),
  INDEX `PrimaryPhysician.physicianid_SocialHistory.physicianid` (`physicianid` ASC),
  INDEX `EducationLevel.educationid_SocialHistory.educationid` (`educationid` ASC),
  INDEX `HeadofHousehold.housestatid_SocialHistory.housestatid` (`housestatid` ASC),
  INDEX `MedicalInsurance.insuranceid_SocialHistory.insuranceid` (`insuranceid` ASC),
  INDEX `Disability.disabilityid_SocialHistory.disabilityid` (`disabilityid` ASC),
  INDEX `Veteran.veteranid_SocialHistory.veteranid` (`veteranid` ASC),
  INDEX `CurrentEmployment.employmentid_SocialHistory.employmentid` (`employmentid` ASC),
  INDEX `RelationshipStatus.relationshipid_SocialHistory.relationshipid` (`relationshipid` ASC),
  INDEX `Alcohol.cooperid_SocialHistory.alcoholid` (`alcoholid` ASC),
  INDEX `FoodStamp.foodstampid_SocialHistory.foodstampid` (`foodstampid` ASC),
  INDEX `HomeType.hometypeid_SocialHistory.hometypeid` (`hometypeid` ASC),
  INDEX `Transport.transportid_SocialHistory.transportid` (`transportid` ASC),
  CONSTRAINT `Alcohol.cooperid_SocialHistory.alcoholid`
    FOREIGN KEY (`alcoholid`)
    REFERENCES `datawarehousedb`.`Alcohol` (`alcoholid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `CooperGreen.cooperid_SocialHistory.cooperid`
    FOREIGN KEY (`cooperid`)
    REFERENCES `datawarehousedb`.`CooperGreen` (`cooperid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `CurrentEmployment.employmentid_SocialHistory.employmentid`
    FOREIGN KEY (`employmentid`)
    REFERENCES `datawarehousedb`.`CurrentEmployment` (`employmentid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Disability.disabilityid_SocialHistory.disabilityid`
    FOREIGN KEY (`disabilityid`)
    REFERENCES `datawarehousedb`.`Disability` (`disabilityid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `EducationLevel.educationid_SocialHistory.educationid`
    FOREIGN KEY (`educationid`)
    REFERENCES `datawarehousedb`.`EducationLevel` (`educationid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FoodStamp.foodstampid_SocialHistory.foodstampid`
    FOREIGN KEY (`foodstampid`)
    REFERENCES `datawarehousedb`.`FoodStamp` (`foodstampid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `HeadofHousehold.housestatid_SocialHistory.housestatid`
    FOREIGN KEY (`housestatid`)
    REFERENCES `datawarehousedb`.`HeadofHousehold` (`housestatid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `HomeType.hometypeid_SocialHistory.hometypeid`
    FOREIGN KEY (`hometypeid`)
    REFERENCES `datawarehousedb`.`HomeType` (`hometypeid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `MedicalInsurance.insuranceid_SocialHistory.insuranceid`
    FOREIGN KEY (`insuranceid`)
    REFERENCES `datawarehousedb`.`MedicalInsurance` (`insuranceid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Patient.patientid_SocialHistory.patientid`
    FOREIGN KEY (`patientid`)
    REFERENCES `datawarehousedb`.`Patient` (`patientid`),
  CONSTRAINT `PrimaryPhysician.physicianid_SocialHistory.physicianid`
    FOREIGN KEY (`physicianid`)
    REFERENCES `datawarehousedb`.`PrimaryPhysician` (`physicianid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `RelationshipStatus.relationshipid_SocialHistory.relationshipid`
    FOREIGN KEY (`relationshipid`)
    REFERENCES `datawarehousedb`.`RelationshipStatus` (`relationshipid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Transport.transportid_SocialHistory.transportid`
    FOREIGN KEY (`transportid`)
    REFERENCES `datawarehousedb`.`Transport` (`transportid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Veteran.veteranid_SocialHistory.veteranid`
    FOREIGN KEY (`veteranid`)
    REFERENCES `datawarehousedb`.`Veteran` (`veteranid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 580
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`CurrentSmoker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`CurrentSmoker` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`CurrentSmoker` (
  `currentsmokerid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sid` BIGINT(20) UNSIGNED NOT NULL,
  `startdate` DATE NULL DEFAULT NULL,
  `packsperday` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`currentsmokerid`),
  INDEX `SocialHistory.sid_CurrentSmoker.sid` (`sid` ASC),
  CONSTRAINT `SocialHistory.sid_CurrentSmoker.sid`
    FOREIGN KEY (`sid`)
    REFERENCES `datawarehousedb`.`SocialHistory` (`sid`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`DrugType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`DrugType` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`DrugType` (
  `drugtypeid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `drugtype` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`drugtypeid`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`Mammogram`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`Mammogram` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`Mammogram` (
  `mammogramid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `patientid` BIGINT(20) UNSIGNED NOT NULL,
  `mammogram` DATE NULL DEFAULT NULL COMMENT 'Date of patient\'s most recent mammogram',
  PRIMARY KEY (`mammogramid`),
  INDEX `Patient.patientid_Mammogram.patientid` (`patientid` ASC),
  CONSTRAINT `Patient.patientid_Mammogram.patientid`
    FOREIGN KEY (`patientid`)
    REFERENCES `datawarehousedb`.`Patient` (`patientid`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`PapSmear`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`PapSmear` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`PapSmear` (
  `papsmearid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `patientid` BIGINT(20) UNSIGNED NOT NULL,
  `papsmear` DATE NULL DEFAULT NULL COMMENT 'Date of the patient\'s most recent pap smear',
  PRIMARY KEY (`papsmearid`),
  INDEX `Patient.patientid_PapSmear.patientid` (`patientid` ASC),
  CONSTRAINT `Patient.patientid_PapSmear.patientid`
    FOREIGN KEY (`patientid`)
    REFERENCES `datawarehousedb`.`Patient` (`patientid`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`PastSmoker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`PastSmoker` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`PastSmoker` (
  `pastsmokerid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sid` BIGINT(20) UNSIGNED NOT NULL,
  `startdate` DATE NULL DEFAULT NULL,
  `quitdate` DATE NULL DEFAULT NULL,
  `packsperday` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`pastsmokerid`),
  INDEX `SocialHistory.sid_PastSmoker.sid` (`sid` ASC),
  CONSTRAINT `SocialHistory.sid_PastSmoker.sid`
    FOREIGN KEY (`sid`)
    REFERENCES `datawarehousedb`.`SocialHistory` (`sid`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`PatientAllergy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`PatientAllergy` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`PatientAllergy` (
  `patientallergyid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `allergylistid` BIGINT(20) UNSIGNED NOT NULL,
  `patientid` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`patientallergyid`),
  INDEX `AllergyList.allergylistid_PatientAllergy.patientallergyid` (`allergylistid` ASC),
  INDEX `Patient.patientid_PatientAllergy.patientid` (`patientid` ASC),
  CONSTRAINT `AllergyList.allergylistid_PatientAllergy.patientallergyid`
    FOREIGN KEY (`allergylistid`)
    REFERENCES `datawarehousedb`.`AllergyList` (`allergylistid`),
  CONSTRAINT `Patient.patientid_PatientAllergy.patientid`
    FOREIGN KEY (`patientid`)
    REFERENCES `datawarehousedb`.`Patient` (`patientid`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`ReasonforVisit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`ReasonforVisit` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`ReasonforVisit` (
  `reasonforvisitid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `reasonforvisit` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`reasonforvisitid`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`VisitType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`VisitType` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`VisitType` (
  `visittypeid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `visittype` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`visittypeid`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COMMENT = 'Basic table that provides core system functionallity.  DO NOT CHANGE THIS TABLE!!!!';


-- -----------------------------------------------------
-- Table `datawarehousedb`.`PatientVisit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`PatientVisit` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`PatientVisit` (
  `patientvisitid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `pstat` TEXT NULL DEFAULT NULL,
  `currentdate` DATE NULL DEFAULT NULL,
  `reasonforvisitid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `visittypeid` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `patientid` BIGINT(20) UNSIGNED NOT NULL,
  `socialservicesneeded` TINYINT NULL COMMENT 'boolean indicating whether social services was desired during the visit',
  PRIMARY KEY (`patientvisitid`),
  INDEX `Patient.patientid_PatientVisit.patientid` (`patientid` ASC),
  INDEX `ReasonforVisit.reasonforvisitid_PatientVisit.reasonforvisitid` (`reasonforvisitid` ASC),
  INDEX `VisitType.visittypeid_PatientVisit.visittypeid` (`visittypeid` ASC),
  CONSTRAINT `Patient.patientid_PatientVisit.patientid`
    FOREIGN KEY (`patientid`)
    REFERENCES `datawarehousedb`.`Patient` (`patientid`),
  CONSTRAINT `ReasonforVisit.reasonforvisitid_PatientVisit.reasonforvisitid`
    FOREIGN KEY (`reasonforvisitid`)
    REFERENCES `datawarehousedb`.`ReasonforVisit` (`reasonforvisitid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `VisitType.visittypeid_PatientVisit.visittypeid`
    FOREIGN KEY (`visittypeid`)
    REFERENCES `datawarehousedb`.`VisitType` (`visittypeid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`STI`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`STI` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`STI` (
  `stiid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `patientid` BIGINT(20) UNSIGNED NOT NULL,
  `sti` DATE NULL DEFAULT NULL COMMENT 'Date of patient\'s last STI test',
  PRIMARY KEY (`stiid`),
  INDEX `Patient.patientid_STI.patientid` (`patientid` ASC),
  CONSTRAINT `Patient.patientid_STI.patientid`
    FOREIGN KEY (`patientid`)
    REFERENCES `datawarehousedb`.`Patient` (`patientid`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawarehousedb`.`SocialDrugs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehousedb`.`SocialDrugs` ;

CREATE TABLE IF NOT EXISTS `datawarehousedb`.`SocialDrugs` (
  `socialdrugsid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `drugtypeid` BIGINT(20) UNSIGNED NOT NULL,
  `sid` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`socialdrugsid`),
  INDEX `DrugType.drugtypeid_SocialDrugs.drugtypeid` (`drugtypeid` ASC),
  INDEX `SocialHistory.sid_SocialDrugs.sid` (`sid` ASC),
  CONSTRAINT `DrugType.drugtypeid_SocialDrugs.drugtypeid`
    FOREIGN KEY (`drugtypeid`)
    REFERENCES `datawarehousedb`.`DrugType` (`drugtypeid`),
  CONSTRAINT `SocialHistory.sid_SocialDrugs.sid`
    FOREIGN KEY (`sid`)
    REFERENCES `datawarehousedb`.`SocialHistory` (`sid`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `datawarehousedb`.`Alcohol`
-- -----------------------------------------------------
START TRANSACTION;
USE `datawarehousedb`;
INSERT INTO `datawarehousedb`.`Alcohol` (`alcoholid`, `alcohol`) VALUES (DEFAULT, 'Never');
INSERT INTO `datawarehousedb`.`Alcohol` (`alcoholid`, `alcohol`) VALUES (DEFAULT, 'Quit');
INSERT INTO `datawarehousedb`.`Alcohol` (`alcoholid`, `alcohol`) VALUES (DEFAULT, 'Rarely');
INSERT INTO `datawarehousedb`.`Alcohol` (`alcoholid`, `alcohol`) VALUES (DEFAULT, 'Moderate');
INSERT INTO `datawarehousedb`.`Alcohol` (`alcoholid`, `alcohol`) VALUES (DEFAULT, 'Daily');

COMMIT;


-- -----------------------------------------------------
-- Data for table `datawarehousedb`.`CitizenStatus`
-- -----------------------------------------------------
START TRANSACTION;
USE `datawarehousedb`;
INSERT INTO `datawarehousedb`.`CitizenStatus` (`citizenid`, `citizen`) VALUES (DEFAULT, 'US Citizen');
INSERT INTO `datawarehousedb`.`CitizenStatus` (`citizenid`, `citizen`) VALUES (DEFAULT, 'Permanent');
INSERT INTO `datawarehousedb`.`CitizenStatus` (`citizenid`, `citizen`) VALUES (DEFAULT, 'Undocumented Resident');

COMMIT;


-- -----------------------------------------------------
-- Data for table `datawarehousedb`.`Ethnicity`
-- -----------------------------------------------------
START TRANSACTION;
USE `datawarehousedb`;
INSERT INTO `datawarehousedb`.`Ethnicity` (`ethnicityid`, `ethnicity`) VALUES (DEFAULT, 'Hispanic');
INSERT INTO `datawarehousedb`.`Ethnicity` (`ethnicityid`, `ethnicity`) VALUES (DEFAULT, 'Non-Hispanic');

COMMIT;


-- -----------------------------------------------------
-- Data for table `datawarehousedb`.`Gender`
-- -----------------------------------------------------
START TRANSACTION;
USE `datawarehousedb`;
INSERT INTO `datawarehousedb`.`Gender` (`genderid`, `gender`) VALUES (DEFAULT, 'Male');
INSERT INTO `datawarehousedb`.`Gender` (`genderid`, `gender`) VALUES (DEFAULT, 'Female');
INSERT INTO `datawarehousedb`.`Gender` (`genderid`, `gender`) VALUES (DEFAULT, 'Transgender');

COMMIT;


-- -----------------------------------------------------
-- Data for table `datawarehousedb`.`Race`
-- -----------------------------------------------------
START TRANSACTION;
USE `datawarehousedb`;
INSERT INTO `datawarehousedb`.`Race` (`raceid`, `race`) VALUES (DEFAULT, 'White');
INSERT INTO `datawarehousedb`.`Race` (`raceid`, `race`) VALUES (DEFAULT, 'Black or African American');
INSERT INTO `datawarehousedb`.`Race` (`raceid`, `race`) VALUES (DEFAULT, 'American Indian or Alaska Native');
INSERT INTO `datawarehousedb`.`Race` (`raceid`, `race`) VALUES (DEFAULT, 'Asian');
INSERT INTO `datawarehousedb`.`Race` (`raceid`, `race`) VALUES (DEFAULT, 'Native Hawaiian or Other Pacific Islander');
INSERT INTO `datawarehousedb`.`Race` (`raceid`, `race`) VALUES (DEFAULT, 'Hispanic');

COMMIT;


-- -----------------------------------------------------
-- Data for table `datawarehousedb`.`CooperGreen`
-- -----------------------------------------------------
START TRANSACTION;
USE `datawarehousedb`;
INSERT INTO `datawarehousedb`.`CooperGreen` (`cooperid`, `cooper`) VALUES (DEFAULT, 'Yes');
INSERT INTO `datawarehousedb`.`CooperGreen` (`cooperid`, `cooper`) VALUES (DEFAULT, 'No');

COMMIT;


-- -----------------------------------------------------
-- Data for table `datawarehousedb`.`CurrentEmployment`
-- -----------------------------------------------------
START TRANSACTION;
USE `datawarehousedb`;
INSERT INTO `datawarehousedb`.`CurrentEmployment` (`employmentid`, `employment`) VALUES (DEFAULT, 'Yes');
INSERT INTO `datawarehousedb`.`CurrentEmployment` (`employmentid`, `employment`) VALUES (DEFAULT, 'No');

COMMIT;


-- -----------------------------------------------------
-- Data for table `datawarehousedb`.`Disability`
-- -----------------------------------------------------
START TRANSACTION;
USE `datawarehousedb`;
INSERT INTO `datawarehousedb`.`Disability` (`disabilityid`, `disability`) VALUES (DEFAULT, 'Yes');
INSERT INTO `datawarehousedb`.`Disability` (`disabilityid`, `disability`) VALUES (DEFAULT, 'No');

COMMIT;


-- -----------------------------------------------------
-- Data for table `datawarehousedb`.`EducationLevel`
-- -----------------------------------------------------
START TRANSACTION;
USE `datawarehousedb`;
INSERT INTO `datawarehousedb`.`EducationLevel` (`educationid`, `education`) VALUES (DEFAULT, 'Some High School');
INSERT INTO `datawarehousedb`.`EducationLevel` (`educationid`, `education`) VALUES (DEFAULT, 'High School Diploma');
INSERT INTO `datawarehousedb`.`EducationLevel` (`educationid`, `education`) VALUES (DEFAULT, 'GED');
INSERT INTO `datawarehousedb`.`EducationLevel` (`educationid`, `education`) VALUES (DEFAULT, 'Some College');
INSERT INTO `datawarehousedb`.`EducationLevel` (`educationid`, `education`) VALUES (DEFAULT, 'College');
INSERT INTO `datawarehousedb`.`EducationLevel` (`educationid`, `education`) VALUES (DEFAULT, 'Post-graduate');

COMMIT;


-- -----------------------------------------------------
-- Data for table `datawarehousedb`.`FoodStamp`
-- -----------------------------------------------------
START TRANSACTION;
USE `datawarehousedb`;
INSERT INTO `datawarehousedb`.`FoodStamp` (`foodstampid`, `foodstamp`) VALUES (DEFAULT, 'Yes');
INSERT INTO `datawarehousedb`.`FoodStamp` (`foodstampid`, `foodstamp`) VALUES (DEFAULT, 'No');

COMMIT;


-- -----------------------------------------------------
-- Data for table `datawarehousedb`.`HeadofHousehold`
-- -----------------------------------------------------
START TRANSACTION;
USE `datawarehousedb`;
INSERT INTO `datawarehousedb`.`HeadofHousehold` (`housestatid`, `housestat`) VALUES (DEFAULT, 'Yes');
INSERT INTO `datawarehousedb`.`HeadofHousehold` (`housestatid`, `housestat`) VALUES (DEFAULT, 'No');

COMMIT;


-- -----------------------------------------------------
-- Data for table `datawarehousedb`.`HomeType`
-- -----------------------------------------------------
START TRANSACTION;
USE `datawarehousedb`;
INSERT INTO `datawarehousedb`.`HomeType` (`hometypeid`, `hometype`) VALUES (DEFAULT, 'Homeless');
INSERT INTO `datawarehousedb`.`HomeType` (`hometypeid`, `hometype`) VALUES (DEFAULT, 'Homeless Shelter');
INSERT INTO `datawarehousedb`.`HomeType` (`hometypeid`, `hometype`) VALUES (DEFAULT, 'Rental House/Apartment');
INSERT INTO `datawarehousedb`.`HomeType` (`hometypeid`, `hometype`) VALUES (DEFAULT, 'Personal Residence');

COMMIT;


-- -----------------------------------------------------
-- Data for table `datawarehousedb`.`MedicalInsurance`
-- -----------------------------------------------------
START TRANSACTION;
USE `datawarehousedb`;
INSERT INTO `datawarehousedb`.`MedicalInsurance` (`insuranceid`, `insurance`) VALUES (DEFAULT, 'Yes');
INSERT INTO `datawarehousedb`.`MedicalInsurance` (`insuranceid`, `insurance`) VALUES (DEFAULT, 'No');

COMMIT;


-- -----------------------------------------------------
-- Data for table `datawarehousedb`.`PrimaryPhysician`
-- -----------------------------------------------------
START TRANSACTION;
USE `datawarehousedb`;
INSERT INTO `datawarehousedb`.`PrimaryPhysician` (`physicianid`, `physician`) VALUES (DEFAULT, 'Yes');
INSERT INTO `datawarehousedb`.`PrimaryPhysician` (`physicianid`, `physician`) VALUES (DEFAULT, 'No');

COMMIT;


-- -----------------------------------------------------
-- Data for table `datawarehousedb`.`RelationshipStatus`
-- -----------------------------------------------------
START TRANSACTION;
USE `datawarehousedb`;
INSERT INTO `datawarehousedb`.`RelationshipStatus` (`relationshipid`, `relationship`) VALUES (DEFAULT, 'Never married');
INSERT INTO `datawarehousedb`.`RelationshipStatus` (`relationshipid`, `relationship`) VALUES (DEFAULT, 'Married/Partnered');
INSERT INTO `datawarehousedb`.`RelationshipStatus` (`relationshipid`, `relationship`) VALUES (DEFAULT, 'Separated');
INSERT INTO `datawarehousedb`.`RelationshipStatus` (`relationshipid`, `relationship`) VALUES (DEFAULT, 'Divorced');
INSERT INTO `datawarehousedb`.`RelationshipStatus` (`relationshipid`, `relationship`) VALUES (DEFAULT, 'Widowed');

COMMIT;


-- -----------------------------------------------------
-- Data for table `datawarehousedb`.`Transport`
-- -----------------------------------------------------
START TRANSACTION;
USE `datawarehousedb`;
INSERT INTO `datawarehousedb`.`Transport` (`transportid`, `transport`) VALUES (DEFAULT, 'Walk/Bike');
INSERT INTO `datawarehousedb`.`Transport` (`transportid`, `transport`) VALUES (DEFAULT, 'Public Transportation');
INSERT INTO `datawarehousedb`.`Transport` (`transportid`, `transport`) VALUES (DEFAULT, 'Personal Vehicle');
INSERT INTO `datawarehousedb`.`Transport` (`transportid`, `transport`) VALUES (DEFAULT, 'Ride from Friend/Family');

COMMIT;


-- -----------------------------------------------------
-- Data for table `datawarehousedb`.`Veteran`
-- -----------------------------------------------------
START TRANSACTION;
USE `datawarehousedb`;
INSERT INTO `datawarehousedb`.`Veteran` (`veteranid`, `veteran`) VALUES (DEFAULT, 'Yes');
INSERT INTO `datawarehousedb`.`Veteran` (`veteranid`, `veteran`) VALUES (DEFAULT, 'No');

COMMIT;


-- -----------------------------------------------------
-- Data for table `datawarehousedb`.`ReasonforVisit`
-- -----------------------------------------------------
START TRANSACTION;
USE `datawarehousedb`;
INSERT INTO `datawarehousedb`.`ReasonforVisit` (`reasonforvisitid`, `reasonforvisit`) VALUES (DEFAULT, 'Recent Problem (<2 weeks), ex. new back pain');
INSERT INTO `datawarehousedb`.`ReasonforVisit` (`reasonforvisitid`, `reasonforvisit`) VALUES (DEFAULT, 'Ongoing Problem (>2 weeks), ex. high blood pressure');
INSERT INTO `datawarehousedb`.`ReasonforVisit` (`reasonforvisitid`, `reasonforvisit`) VALUES (DEFAULT, 'Smoking/Alcohol/Drug Cessation');
INSERT INTO `datawarehousedb`.`ReasonforVisit` (`reasonforvisitid`, `reasonforvisit`) VALUES (DEFAULT, 'Mental Health');

COMMIT;


-- -----------------------------------------------------
-- Data for table `datawarehousedb`.`VisitType`
-- -----------------------------------------------------
START TRANSACTION;
USE `datawarehousedb`;
INSERT INTO `datawarehousedb`.`VisitType` (`visittypeid`, `visittype`) VALUES (DEFAULT, 'New Patient');
INSERT INTO `datawarehousedb`.`VisitType` (`visittypeid`, `visittype`) VALUES (DEFAULT, 'Returning Patient');

COMMIT;

